---
- hosts: "{{ myhosts | default('local') }}"
  tasks:
    - name: Pull latest version from git
      git:
        repo: "{{ repo }}"
        dest: "{{ dest }}"
        # do not handle submodules
        recursive: false
        version: "{{ branch | default('HEAD') }}"
        clone: yes
        update: yes
      register: git_result

    - name: Get latest commit message
      shell: git log --pretty="%h - %cd - %s" -n 1
      args:
        chdir: "{{ dest }}"
      register: output

    - debug:
        msg: "{{ output.stdout_lines }}"
      when: output is defined and output.stdout_lines is defined

    - name: Check dot envs
      include_tasks: dotenv-check.yml
      loop:
        - icarus_db
        - icarus_be
        - icarus_ui

    - name: Compose new version
      shell: "docker-compose -f docker-compose.yml -f docker-compose.override.yml up --build -d"
      args:
        chdir: "{{ dest }}"
      when: force_compose or (git_result.before != git_result.after)

    - name: Check docker containers
      include_tasks: docker-check.yml
      loop: "{{ docker_containers }}"
