- hosts: local
  gather_facts: no
  tasks:
    - name: "Check that a page returns a status 200"
      uri:
        url: "{{ item.url }}"
        validate_certs: no
        return_content: yes
      register: this
      failed_when: "item.text not in this.content"
      loop:
        - url: https://svip.ch
          text: SVIP-O
        - url: https://svip-test.nexus.ethz.ch
          text: SVIP-O
        - url: https://svip-dev.nexus.ethz.ch
          text: SVIP-O
